# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: otelcol-build
before:
  hooks:
    - sh -c 'cd ./cmd/otelcol-agent && go mod tidy'
    - sh -c 'cd ./cmd/otelcol-clickhouse && go mod tidy'

builds:
  - id: otelcol-agent
    dir: ./cmd/otelcol-agent
    binary: otelcol-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: otelcol-clickhouse
    dir: ./cmd/otelcol-clickhouse
    binary: otelcol-clickhouse
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - id: otelcol-agent
    package_name: otelcol-agent
    ids:
      - otelcol-agent
    license: Apache 2.0
    formats:
      - deb
    maintainer: ophum
    contents:
      - dst: /lib/systemd/system/otelcol-agent.service
        src: misc/files/otelcol-agent.service
        type: config
      - dst: /etc/otelcol-agent/config.yaml
        src: misc/files/otelcol-agent-config.yaml
        type: config
      - dst: /etc/otelcol-agent/otelcol-agent.conf
        src: misc/files/otelcol-agent.conf
    scripts:
      preinstall: misc/files/otelcol-agent-preinstall.sh
      postinstall: misc/files/otelcol-agent-postinstall.sh
  - id: otelcol-clickhouse
    package_name: otelcol-clickhouse
    ids:
      - otelcol-clickhouse
    license: Apache 2.0
    formats:
      - deb
    maintainer: ophum
    contents:
      - dst: /lib/systemd/system/otelcol-clickhouse.service
        src: misc/files/otelcol-clickhouse.service
        type: config
      - dst: /etc/otelcol-clickhouse/config.yaml
        src: misc/files/otelcol-clickhouse-config.yaml
        type: config
      - dst: /etc/otelcol-clickhouse/otelcol-clickhouse.conf
        src: misc/files/otelcol-clickhouse.conf
    scripts:
      preinstall: misc/files/otelcol-clickhouse-preinstall.sh
      postinstall: misc/files/otelcol-clickhouse-postinstall.sh

archives:
  - id: otelcol-agent
    ids:
      - otelcol-agent
    format: binary
  - id: otelcol-clickhouse
    ids:
      - otelcol-clickhouse
    format: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: ophum
    name: otelcol-build
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
